name: mi_card
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/eu.jpg
    - images/icon-whatsapp.png
    - images/icon-instagram.png
    - images/icon-twitter.png

  fonts:
  - family: Pacifico
    fonts:
    - asset: fonts/Pacifico-Regular.ttf

  - family: Source Sans Pro
    fonts:
    - asset: fonts/SourceSansPro-Regular.ttf
  
  - family: Zen Dots
    fonts:
    - asset: fonts/ZenDots-Regular.ttf

  - family: Dancing Script
    fonts:
    - asset: fonts/DancingScript-VariableFont_wght.ttf


